import { motion } from 'framer-motion';
import { Sparkles, Target, Heart, Code2 } from 'lucide-react';
import { Navbar } from '../components/layout/Navbar';
import { Footer } from '../components/layout/Footer';
import { FloatingBackground } from '../components/ui/FloatingBackground';
import { Card } from '../components/ui/Card';
import { GradientText } from '../components/ui/GradientText';

const VALUES = [
  { icon: Target, title: 'Focus', desc: 'One great chat experience, done properly, instead of a hundred half-built ones.' },
  { icon: Heart, title: 'Craft', desc: 'Every animation, spacing value, and micro-interaction is considered on purpose.' },
  { icon: Code2, title: 'Transparency', desc: 'No hidden servers or data collection — the entire app runs in your browser tab.' },
];

export default function AboutPage() {
  return (
    <div className="relative min-h-screen">
      <FloatingBackground />
      <Navbar />
      <main className="mx-auto max-w-4xl px-4 pb-24 pt-16 sm:pt-20">
        <div className="text-center">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-aura-gradient shadow-glow"
          >
            <Sparkles size={28} className="text-white" />
          </motion.div>
          <h1 className="mt-6 font-display text-4xl font-bold sm:text-5xl">
            We think AI chat should feel <GradientText>this good.</GradientText>
          </h1>
          <p className="mx-auto mt-5 max-w-2xl text-current/60">
            Chatty started as an answer to a simple frustration: most AI chat interfaces feel
            like unfinished dashboards. We wanted something that felt considered — the kind
            of interface you'd expect from a product you paid for, built entirely as a
            frontend experience with no server to maintain.
          </p>
        </div>

        <div className="mt-16 grid gap-5 sm:grid-cols-3">
          {VALUES.map(({ icon: Icon, title, desc }) => (
            <Card key={title}>
              <div className="mb-4 grid h-11 w-11 place-items-center rounded-xl bg-aura-gradient shadow-glow">
                <Icon size={20} className="text-white" />
              </div>
              <h3 className="font-display text-lg font-semibold">{title}</h3>
              <p className="mt-1.5 text-sm text-current/60">{desc}</p>
            </Card>
          ))}
        </div>

        <Card className="mt-16">
          <h2 className="font-display text-xl font-semibold">How it's built</h2>
          <p className="mt-2 text-sm text-current/60">
            Chatty is a React 19 + Vite single-page app with no backend whatsoever. Every
            conversation, setting, and theme preference is stored in your browser's local
            storage, and the assistant's replies are generated by a client-side response
            engine — or, if you add your own API key in Settings, sent directly from your
            browser to your provider of choice.
          </p>
        </Card>
      </main>
      <Footer />
    </div>
  );
}
