import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown } from 'lucide-react';
import { Navbar } from '../components/layout/Navbar';
import { Footer } from '../components/layout/Footer';
import { FloatingBackground } from '../components/ui/FloatingBackground';
import { GradientText } from '../components/ui/GradientText';
import { cn } from '../utils/cn';

const FAQS = [
  {
    q: 'Does Chatty have a backend server?',
    a: 'No. This build is intentionally 100% frontend — React 19 and Vite only. All chat history, settings, and theme preferences are stored in your browser\'s local storage.',
  },
  {
    q: 'How does the AI actually respond without a server?',
    a: 'By default, replies are generated by a built-in client-side response engine so the demo works instantly with no setup. If you add your own API key in Settings, your browser will call that provider\'s API directly instead.',
  },
  {
    q: 'Will my chats still be there after I refresh the page?',
    a: 'Yes — conversations, pinned/favorite chats, settings, and your theme choice are all persisted to local storage and reload automatically.',
  },
  {
    q: 'Can I upload PDFs and Word documents?',
    a: 'You can attach images, PDFs, and DOCX files and see them previewed in the composer and message thread. Since there\'s no backend, the app doesn\'t parse their contents — it\'s a UI-complete upload experience.',
  },
  {
    q: 'Does voice input work in every browser?',
    a: 'Voice input and output use the browser\'s built-in Web Speech APIs, which are best supported in Chromium-based browsers (Chrome, Edge). The microphone button hides itself automatically if your browser doesn\'t support it.',
  },
  {
    q: 'Is my data private?',
    a: 'Everything stays on your device unless you explicitly configure your own API key, in which case requests go straight from your browser to that provider — never through any Chatty server, because none exists.',
  },
];

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <div className="relative min-h-screen">
      <FloatingBackground />
      <Navbar />
      <main className="mx-auto max-w-3xl px-4 pb-24 pt-16 sm:pt-20">
        <div className="text-center">
          <h1 className="font-display text-4xl font-bold sm:text-5xl">
            Frequently asked <GradientText>questions</GradientText>
          </h1>
          <p className="mt-4 text-current/60">Can't find what you're looking for? Reach out on the Contact page.</p>
        </div>

        <div className="mt-12 space-y-3">
          {FAQS.map((item, i) => {
            const isOpen = openIndex === i;
            return (
              <div key={item.q} className="glass overflow-hidden rounded-2xl">
                <button
                  onClick={() => setOpenIndex(isOpen ? null : i)}
                  aria-expanded={isOpen}
                  className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left"
                >
                  <span className="font-medium">{item.q}</span>
                  <ChevronDown
                    size={18}
                    className={cn('shrink-0 text-current/50 transition-transform', isOpen && 'rotate-180')}
                  />
                </button>
                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.25, ease: 'easeInOut' }}
                      className="overflow-hidden"
                    >
                      <p className="px-5 pb-5 text-sm text-current/60">{item.a}</p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>
      </main>
      <Footer />
    </div>
  );
}
